"""empty message

Revision ID: 548259631e22
Revises: 8617322be8a8
Create Date: 2023-09-23 00:33:45.541816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548259631e22'
down_revision = '8617322be8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
