"""empty message

<<<<<<<< HEAD:migrations/versions/54d476315e65_.py
Revision ID: 54d476315e65
Revises: 
Create Date: 2023-09-14 23:41:05.139780
========
Revision ID: b23e6bada932
Revises: 
Create Date: 2023-09-14 22:19:54.340568
>>>>>>>> 6a08cda9da8c5041492e2b6be81197850328e4cf:migrations/versions/b23e6bada932_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/54d476315e65_.py
revision = '54d476315e65'
========
revision = 'b23e6bada932'
>>>>>>>> 6a08cda9da8c5041492e2b6be81197850328e4cf:migrations/versions/b23e6bada932_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('age', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=150), nullable=False),
    sa.Column('salt', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservacion_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('user')
    op.drop_table('products')
    # ### end Alembic commands ###
